---
- name: Install Nexus
  hosts: private_machine_az1
  become: true
  gather_facts: false
  vars:
    ansible_user: ubuntu
    ansible_become: true
    ansible_become_method: sudo

  tasks:
  - name: Install necessary packages
    apt:
      name:
        - openjdk-8-jdk
        - unzip
      update_cache: yes

  - name: Download Nexus archive
    get_url:
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      dest: /tmp/latest-unix.tar.gz

  - name: Extract Nexus archive
    unarchive:
      src: /tmp/latest-unix.tar.gz
      dest: /opt
      remote_src: yes

  - name: Start Nexus
    shell: |
      cd /opt/nexus-3.47.1-01/bin/
      ./nexus start
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/



- name: Install SonarQube 
  hosts: private_machine_az2
  become: true
  tasks:

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install Java
    apt:
      name: openjdk-11-jdk
      state: latest

  - name: Download SonarQube archive
    get_url:
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
      dest: /tmp/sonarqube.zip
  
  - name: Install unzip package
    apt:
      name: unzip
      state: present
  
  - name: Extract SonarQube archive
    unarchive:
      src: /tmp/sonarqube.zip
      dest: /opt
      remote_src: yes

  - name: start SonarQube
    shell: |
      cd /opt/sonarqube-7.9.3/bin/linux-x86-64
      ./sonar.sh start
